### ISSUE TITLE
Total STX locked calculation is slightly off

### ISSUE THREAD

**Issue by jcnelson** [stacking-club/stacking.club#3]
I've noticed that the "total stacked" number for a reward cycle is slightly higher than what gets reported by the node (198,498,394.975560 vs 199,564,835).  I'm getting the 198k number via the `get-total-ustx-stacked` public read-only function in the PoX contract, as follows:

```bash
host="seed-0.mainnet.stacks.co:20443"

# pox info
pox_info="$(curl -sf http://$host/v2/pox)"

# which reward cycle are we in?
cur_reward_cycle="$(echo "$pox_info" | jq -r '.reward_cycle_id')"
next_reward_cycle="$((cur_reward_cycle + 1))"

# call read-only get-total-ustx-stacked
next_reward_cycle_clarity_value="$(printf "0x01%032x" "$next_reward_cycle")"
body="{
   \"sender\": \"SP31DA6FTSJX2WGTZ69SFY11BH51NZMB0ZW97B5P0.get-info\",
   \"arguments\": [
        \"$next_reward_cycle_clarity_value\"
   ] 
}"

body_len=${#body}

ustx_hex="$(echo "$body" | curl -sf -X POST -H "content-type: application/json" -H "content-length: $body_len" --data-binary @- "http://$host/v2/contracts/call-read/SP000000000000000000002Q6VF78/pox/get-total-ustx-stacked" | \
        jq -r '.result' | \
        sed -r 's/0x010*//g')"

# how many uSTX are participating
participation="$(printf "%d" $((16#$ustx_hex)))"

echo -n "STX locked: "
echo "scale=6; $participation / 1000000" | bc
```

I'm not sure how stacking.club is getting this calculation on the back-end, but I think it's being calculated from the event stream instead of just hitting up the node directly?

**Comment by aulneau** [comment]
Hey @jcnelson!

Thanks for posting this. This might be an issue that has to wait until @hstove is back in action. My understanding is that we have persisted data for all `stack-stx` and `delegate-stack-stx` transactions that are accessible via the `stacks-node-api`, and we are summing the data for the stacked amount from each transaction associated with a given cycle. 

Could this actually be an underlying issue with `stacks-blockchain-api`? I would assume that if anyone else were to call this endpoint: `https://stacks-node-api.stacks.co/extended/v1/address/SP000000000000000000002Q6VF78.pox/transactions?limit=50`, paginate through all of them, extract all the `stack-stx` and `delegate-stack-stx` contract-calls that match a given cycle, and sum the amounts, it should equal what we have on stacking.club.
