### ISSUE TITLE
Rendering issues

### ISSUE THREAD

**Issue by diwakergupta** [stacking-club/stacking.club#4]
Often the first load of a page would not render correctly, and show an "unexpected error occurred" message (see screenshot below). Reloading the page usually fixes this. I've noticed this on multiple pages (Chrome, MacOS Big Sur).

<img width="1208" alt="Screen Shot 2021-02-24 at 12 29 26 PM" src="https://user-images.githubusercontent.com/15990/109040712-36206300-769c-11eb-80dc-e13841476a14.png">

**Comment by aulneau** [comment]
Thanks @diwakergupta :) I have seen this too but have yet been able to determine why it happens. I've added some better error pages and sentry, so hopefully I'll be able to learn what the issue is.
