### ISSUE TITLE
Cycle diagram with short PoB phase

### ISSUE THREAD

**Issue by agraebe** [stacking-club/stacking.club#7]
In the current cycle, there is a short PoB phase. The label is overlapping:

<img width="1065" alt="Screen Shot 2021-03-29 at 6 03 45 PM" src="https://user-images.githubusercontent.com/1671228/112918201-35bf2180-90b9-11eb-8fa5-a4abb3891be5.png">

**Comment by aulneau** [comment]
This should be resolved now :) https://stacking.club/cycles/current
